### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by roughpandaz** [mtlynch/ansible-role-storj#15]
It seems like you are using Ansible to set up the entire environment. Curious why you didn't build a Docker image first and use just Ansible as a deployment tool?

**Comment by mtlynch** [comment]
I'm better at Ansible than I am at Docker.

I want to be able to deploy Storj on remote machines, but I'm not sure how to do that with Docker + Ansible.

Would I have to do something like this?

1. Use Ansible to install Docker to remote machine
1. Ansible tells Docker to create Storj container
1. Use Ansible to connect to remote machine, then connect to Docker within remote machine to deploy Storj

I don't know how to do (3). I know how to manage a container when Docker is running as the same machine as the control node (using `ansible_connection=docker`), but I don't know how to go control node > remote machine > container on remote machine through Ansible.

What's the boundary between where I stop doing things in Docker and start doing them in Ansible? My intuition is that [this part](https://github.com/mtlynch/ansible-role-storj/blob/56107066d435c106945d5e3a7ff3dcb8007027e3/tasks/main.yml#L2-L27) should be captured in the Docker container and [this part](https://github.com/mtlynch/ansible-role-storj/blob/56107066d435c106945d5e3a7ff3dcb8007027e3/tasks/main.yml#L29-L99) should be Ansible.

If you have insight here, I'd greatly appreciate it.

**Comment by roughpandaz** [comment]
For (3), it might be possible to control a remote docker container through Ansible using [this module](http://docs.ansible.com/ansible/latest/modules/docker_container_module.html#docker-container). However, I would assume that once the Storj container is started, there will be very little interaction with it other than to perform health-checks?

I think [this part](https://github.com/mtlynch/ansible-role-storj/blob/56107066d435c106945d5e3a7ff3dcb8007027e3/tasks/main.yml#L29-L99) can just be swapped out to deploy a pre-built docker image.

I haven't done that much with Ansible, but you can use docker-machine to interact with a remote instance [like this](https://stackoverflow.com/questions/43505196/how-to-deploy-a-docker-container-on-a-remote-ubuntu-server). Although it seems like Ansible provides much more flexibility in orchestrating the set-up of the machine and managing multiple instances.

**Comment by RongxinZhang** [comment]
Also, I just saw that you are in NYC.
I'm currently a grad student at Cornell Tech. If you have time I'd love to grab coffee and discuss this project with you more! I don't use twitter and I couldn't find your email so here's mine: mrrongxin@gmail.com. Haha

**Comment by mtlynch** [comment]
>I think this part can just be swapped out to deploy a pre-built docker image.

I don't think that's possible because it relies on values that can't be baked into the image, such as the payout addresses and the amount of storage the user wants to share.

>I haven't done that much with Ansible, but you can use docker-machine to interact with a remote instance like this. Although it seems like Ansible provides much more flexibility in orchestrating the set-up of the machine and managing multiple instances.

The part I'm still missing is how you run an Ansible playbook on a container on a remote machine. I can find documentation for how to use Ansible to deploy a Docker image on a remote machine. I can find documentation for how to use Ansible to run a playbook against a Docker container on a *local* machine. But I can't figure out how to have Ansible pull down the image on the remote machine, start the container, then run the rest of the playbook within the container.

The only way I can think to do it would be to use Ansible to install Ansible on the remote machine, then kick off ansible-playbook on the remote machine to interact with the Docker container locally. But that would be super contrived:

```
 ---------------                     -----------------------------
| local machine | ---- Ansible ---> |      remote machine         |
 ---------------                    |            |                |
                                    |            |                |
                                    |         Ansible             |
                                    |            |                |
                                    |            |                |
                                    |            v                |
                                    |        ---------            |
                                    |       | Docker  |           |
                                    |        ---------            |
                                     -----------------------------
```

**Comment by roughpandaz** [comment]
One way I can think of running a pre-built docker image that needs run-time variables is through environment variables like [this](https://docs.docker.com/engine/reference/run/#env-environment-variables).

I agree with the second point, after seeing the new video you posted of the demo, it does seem to be a complex workaround for something that ansible can do on its own.

From your experience with running nodes, what is the machine resource usage on these?

**Comment by mtlynch** [comment]
>From your experience with running nodes, what is the machine resource usage on these?

It's extremely low, at least for young nodes. I'm running 10 farmers on a GCE n1-standard-2 instance and it barely breaks 1% CPU usage:

![image](https://user-images.githubusercontent.com/7783288/38529024-818ac604-3c30-11e8-9930-752ea0202132.png)

But they're also not hosting much data:

```
storj-multi-host | SUCCESS | rc=0 >>

┌─────────────────────────────────────────────┬─────────┬──────────┬──────────┬─────────┬───────────────┬─────────┬──────────┬───────────┬──────────────┐
│ Node                                        │ Status  │ Uptime   │ Restarts │ Peers   │ Allocs        │ Delta   │ Port     │ Shared    │ Bridges      │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ 5156e4717f14cf19519507a7c6e0bf2816763609    │ running │ 16d 19h… │ 0        │ 42      │ 2351          │ 1ms     │ 6000     │ 2.01MB    │ connected    │
│   → /opt/storj/shared/0x161441Efd42171687d… │         │          │          │         │ 18 received   │         │ (TCP)    │ (0%)      │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ 87c98e525363fb0b305c65f043b497b30ed5a9ba    │ running │ 16d 19h… │ 0        │ 103     │ 2948          │ 0ms     │ 6001     │ 23.26MB   │ connected    │
│   → /opt/storj/shared/0xe2c1042ae7192dcae9… │         │          │          │         │ 26 received   │         │ (TCP)    │ (1%)      │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ 707db123a434e41e06a4723e304a26556758b8da    │ running │ 16d 19h… │ 0        │ 145     │ 2372          │ 0ms     │ 6002     │ 5.36MB    │ connected    │
│   → /opt/storj/shared/0xd064bd4c0d1efa0271… │         │          │          │         │ 24 received   │         │ (TCP)    │ (0%)      │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ 1ef2b2075c0d7cbb14f9e5d71714af2c5f60ef0c    │ running │ 16d 19h… │ 0        │ 40      │ 2385          │ -1ms    │ 6003     │ 10.03MB   │ connected    │
│   → /opt/storj/shared/0xea66fe9ff2a9ef78f7… │         │          │          │         │ 24 received   │         │ (TCP)    │ (0%)      │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ 35358359f220d2251d11a34c448d30f9b1ea06f9    │ running │ 16d 19h… │ 0        │ 59      │ 2274          │ 0ms     │ 6004     │ 21.07MB   │ connected    │
│   → /opt/storj/shared/0xc32292b7558c21530c… │         │          │          │         │ 12 received   │         │ (TCP)    │ (1%)      │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ 983fbd8c68d322c21c9fd3e5cd38b1810296e20a    │ running │ 16d 19h… │ 0        │ 101     │ 2939          │ 0ms     │ 6005     │ 38.1MB    │ connected    │
│   → /opt/storj/shared/0x39e067e87b0ad5943f… │         │          │          │         │ 44 received   │         │ (TCP)    │ (1%)      │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ d7d3d826013c53668fe283b5a2765d0856ede729    │ running │ 16d 19h… │ 0        │ 109     │ 2003          │ 0ms     │ 6006     │ 3.01MB    │ connected    │
│   → /opt/storj/shared/0x5b20306ebe43c7e67a… │         │          │          │         │ 22 received   │         │ (TCP)    │ (0%)      │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ 5205621f56345489d1e84978cabca7c77701a586    │ running │ 16d 19h… │ 0        │ 96      │ 1904          │ 0ms     │ 6007     │ 11.04MB   │ connected    │
│   → /opt/storj/shared/0xaa3e0592028a889eab… │         │          │          │         │ 26 received   │         │ (TCP)    │ (0%)      │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ ca0f33252f28d0fce25b587d1c6cad0b56957071    │ running │ 16d 19h… │ 0        │ 102     │ 2393          │ 0ms     │ 6008     │ 972B      │ connected    │
│   → /opt/storj/shared/0x81f3182468ed9e4a46… │         │          │          │         │ 6 received    │         │ (TCP)    │ (0%)      │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ 46c46f04fc1cfbe9dc6b477329a45e1c0a94266e    │ running │ 16d 19h… │ 0        │ 127     │ 2482          │ 1ms     │ 6009     │ 40.13MB   │ connected    │
│   → /opt/storj/shared/0xb1323b3da6acd68d15… │         │          │          │         │ 26 received   │         │ (TCP)    │ (1%)      │              │
└─────────────────────────────────────────────┴─────────┴──────────┴──────────┴─────────┴───────────────┴─────────┴──────────┴───────────┴──────────────┘
```

**Comment by roughpandaz** [comment]
Very interesting, thanks for the info!
